# Generated by Django 5.2.1 on 2025-05-31 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('scanner', '0002_scan_authorization_required_scan_compliance_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='authorization',
            field=models.ForeignKey(blank=True, help_text='Authorization for this scan (required for active scans)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='compliance.domainauthorization'),
        ),
    ]
