# Generated by Django 5.2.1 on 2025-06-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('scanner', '0003_alter_scan_authorization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useragreement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='user',
        ),
        migrations.AlterField(
            model_name='scan',
            name='authorization',
            field=models.ForeignKey(blank=True, help_text='Domain authorization required for active scanning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='compliance.domainauthorization'),
        ),
        migrations.DeleteModel(
            name='ScanAuthorization',
        ),
        migrations.DeleteModel(
            name='UserAgreement',
        ),
    ]
