# Generated by Django 5.2 on 2025-04-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='scan',
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='scan_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='scan_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
