# Generated by Django 5.2 on 2025-05-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analyzer', '0002_remove_aianalysis_scan_aianalysis_scan_identifier_and_more'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='scanner.scan')),
            ],
        ),
    ]
