# Generated by Django 5.2 on 2025-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='security_score',
            field=models.IntegerField(default=100),
        ),
    ]
