# Generated by Django 5.2 on 2025-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_security_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category_scores',
            field=models.JSONField(default=dict),
        ),
    ]
