// Alert Action Types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const CLEAR_ALL_ALERTS = "CLEAR_ALL_ALERTS";

// Authentication Action Types
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

// Scan Action Types
export const SCAN_REQUEST = "SCAN_REQUEST";
export const SCAN_SUCCESS = "SCAN_SUCCESS";
export const SCAN_ERROR = "SCAN_ERROR";

export const SCAN_STATUS_REQUEST = "SCAN_STATUS_REQUEST";
export const SCAN_STATUS_SUCCESS = "SCAN_STATUS_SUCCESS";
export const SCAN_STATUS_ERROR = "SCAN_STATUS_ERROR";

export const SCAN_RESULTS_REQUEST = "SCAN_RESULTS_REQUEST";
export const SCAN_RESULTS_SUCCESS = "SCAN_RESULTS_SUCCESS";
export const SCAN_RESULTS_ERROR = "SCAN_RESULTS_ERROR";

export const SCAN_CANCEL_REQUEST = "SCAN_CANCEL_REQUEST";
export const SCAN_CANCEL_SUCCESS = "SCAN_CANCEL_SUCCESS";
export const SCAN_CANCEL_ERROR = "SCAN_CANCEL_ERROR";

export const RECENT_SCANS_REQUEST = "RECENT_SCANS_REQUEST";
export const RECENT_SCANS_SUCCESS = "RECENT_SCANS_SUCCESS";
export const RECENT_SCANS_ERROR = "RECENT_SCANS_ERROR";

export const CLEAR_SCAN_STATE = "CLEAR_SCAN_STATE";

// Report Action Types
export const REPORT_LIST_REQUEST = "REPORT_LIST_REQUEST";
export const REPORT_LIST_SUCCESS = "REPORT_LIST_SUCCESS";
export const REPORT_LIST_ERROR = "REPORT_LIST_ERROR";

export const REPORT_DETAILS_REQUEST = "REPORT_DETAILS_REQUEST";
export const REPORT_DETAILS_SUCCESS = "REPORT_DETAILS_SUCCESS";
export const REPORT_DETAILS_ERROR = "REPORT_DETAILS_ERROR";

export const REPORT_GENERATE_REQUEST = "REPORT_GENERATE_REQUEST";
export const REPORT_GENERATE_SUCCESS = "REPORT_GENERATE_SUCCESS";
export const REPORT_GENERATE_ERROR = "REPORT_GENERATE_ERROR";

export const REPORT_DELETE_REQUEST = "REPORT_DELETE_REQUEST";
export const REPORT_DELETE_SUCCESS = "REPORT_DELETE_SUCCESS";
export const REPORT_DELETE_ERROR = "REPORT_DELETE_ERROR";

// Dashboard Action Types
export const DASHBOARD_DATA_REQUEST = "DASHBOARD_DATA_REQUEST";
export const DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS";
export const DASHBOARD_DATA_ERROR = "DASHBOARD_DATA_ERROR";

export const SECURITY_SCORE_REQUEST = "SECURITY_SCORE_REQUEST";
export const SECURITY_SCORE_SUCCESS = "SECURITY_SCORE_SUCCESS";
export const SECURITY_SCORE_ERROR = "SECURITY_SCORE_ERROR";

export const RECENT_ALERTS_REQUEST = "RECENT_ALERTS_REQUEST";
export const RECENT_ALERTS_SUCCESS = "RECENT_ALERTS_SUCCESS";
export const RECENT_ALERTS_ERROR = "RECENT_ALERTS_ERROR";
